plugins {
    id 'java'
    id 'java-library'
	id 'maven-publish'
    id 'signing'
}

group = 'io.github.sandydunlop'
version = '0.1.0'

base {
    archivesName = "cupra"
}

apply plugin: 'java'
apply plugin: 'java-library'
apply plugin: 'maven-publish' 
apply plugin: 'signing' 

repositories {
    mavenCentral()
    google()
}

dependencies {
    testImplementation libs.junit.jupiter
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'

    implementation ("commons-io:commons-io:${project.commons_io_version}")
    implementation ("org.apache.commons:commons-collections4:${project.commons_collections_version}")	
	implementation ("org.apache.commons:commons-lang3:${project.commons_lang_version}")
    implementation ("org.apache.logging.log4j:log4j-core:${project.commons_logging_version}")
    implementation ("com.dorkbox:Notify:${project.notify_version}")
}

tasks.withType(JavaCompile).configureEach {
	it.options.release = 21
}

// Apply a specific Java toolchain to ease working on different environments.
java {
    withJavadocJar()
	withSourcesJar()
	sourceCompatibility = JavaVersion.VERSION_21
	targetCompatibility = JavaVersion.VERSION_21
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

tasks.named('test') {
    // Use JUnit Platform for unit tests.
    useJUnitPlatform()
}

jar.doLast {
    ant.checksum file: archivePath
}

signing {
    sign publishing.publications
}

// configure the maven publication
publishing {
    publications {
        myPub(MavenPublication) {
            from components.java
            pom {
                name = 'Cupra'
                description = 'Cupra UI Framework'
                url = 'https://github.com/sandydunlop/cupra'
                licenses {
                    license {
                        name = 'MIT License'
                        url = 'https://raw.githubusercontent.com/sandydunlop/cupra/refs/heads/dev/LICENSE'
                    }
                }
                developers {
                    developer {
                        id = 'sandydunlop'
                        name = 'Sandy Dunlop'
                        email = 'sandy.dunlop@gmail.com'
                    }
                }
                scm {
                    connection = 'scm:git:git://github.com/sandydunlop/cupra.git'
                    developerConnection = 'scm:git:ssh://github.com:sandydunlop/cupra.git'
                    url = 'https://github.com/sandydunlop/cupra'
                }
            }
        }
    }

	// See https://docs.gradle.org/current/userguide/publishing_maven.html for information on how to set up publishing.
	repositories {
        maven {
            name = "LocalMavenWithChecksums"
            url = uri(layout.buildDirectory.dir("staging-deploy"))
        }
    }
}
